### PR TITLE
Plat 1045 fork to staging

### PR DESCRIPTION
**Pull request by aluguern**
This change is [Reviewable](https://reviewable.io/reviews/nativetouch/gonfork/1)

### CODE REVIEW

**Comment by JesseEmond** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[nfork/inbound.go, line 308 \[r2\]](https://reviewable.io:443/reviews/nativetouch/gonfork/1#-KIZ8z3p23Zfl9jeJIqY:-KIZ8z3p23Zfl9jeJIqZ:-1708723687) ([raw file](https://github.com/nativetouch/gonfork/blob/a1647f1dd593800e0c10117bd95e5fed47fb6b15/nfork/inbound.go#L308)):*
> ```Go
> 	t0 := time.Now()
> 
> 	//host, scheme := inbound.parseAddr(addr)
> ```

I guess we can remove this commented line now (and get rid of `parseAddr` at the same time if that's its only usage).

---

*[nfork/inbound.go, line 322 \[r2\]](https://reviewable.io:443/reviews/nativetouch/gonfork/1#-KIZ9ciSBM0CusGSrAKO:-KIZ9ciSBM0CusGSrAKP:1075279769) ([raw file](https://github.com/nativetouch/gonfork/blob/a1647f1dd593800e0c10117bd95e5fed47fb6b15/nfork/inbound.go#L322)):*
> ```Go
> 	newReq.Host = parsedURL.Host
> 
> 	hasPath := len(path) > 0
> ```

Suggestion: renaming this to something along the lines of `hasEnforcedPath` or maybe just leave a comment to indicate that setting the path will force gonfork to preserve the path that is in the config? I'm just wondering how we could make the purpose of the 2 `if` code paths more obvious.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/1)*

**Comment by anordell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[nfork/inbound.go, line 27 \[r2\]](https://reviewable.io:443/reviews/nativetouch/gonfork/1#-KIZEBqwhZ71c1TF19eB:-KIZEBqx-Yhf4FEHQA4U:180030187) ([raw file](https://github.com/nativetouch/gonfork/blob/a1647f1dd593800e0c10117bd95e5fed47fb6b15/nfork/inbound.go#L27)):*
> ```Go
> 	// Host is the address where HTTP requests
> 	// should be redirected to. Addresses should be of the for
> 	// <scheme>://<host>:<port>.
> ```

Is scheme the actually name for that part of an adress?

---

*[nfork/inbound.go, line 322 \[r2\]](https://reviewable.io:443/reviews/nativetouch/gonfork/1#-KIZ9ciSBM0CusGSrAKO:-KIZE3ijC-MtiUK653oA:1751096411) ([raw file](https://github.com/nativetouch/gonfork/blob/a1647f1dd593800e0c10117bd95e5fed47fb6b15/nfork/inbound.go#L322)):*
<details><summary><i>Previously, JesseEmond (JesseEmond) wrote…</i></summary>
> Suggestion: renaming this to something along the lines of `hasEnforcedPath` or maybe just leave a comment to indicate that setting the path will force gonfork to preserve the path that is in the config? I'm just wondering how we could make the purpose of the 2 `if` code paths more obvious.
</details>
+1. Or comment if else

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/1)*

**Comment by aluguern** [comment]
*[nfork/inbound.go, line 27 \[r2\]](https://reviewable.io:443/reviews/nativetouch/gonfork/1#-KIZEBqwhZ71c1TF19eB:-KIZEKAY4Et07vRog2we:406300160) ([raw file](https://github.com/nativetouch/gonfork/blob/a1647f1dd593800e0c10117bd95e5fed47fb6b15/nfork/inbound.go#L27)):*
<details><summary><i>Previously, anordell wrote…</i></summary>
> Is scheme the actually name for that part of an adress?
</details>
Yes it is!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/1)*

**Comment by aluguern** [comment]
Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[nfork/inbound.go, line 308 \[r2\]](https://reviewable.io:443/reviews/nativetouch/gonfork/1#-KIZ8z3p23Zfl9jeJIqY:-KIZFFmozBks368lcp4p:-499146009) ([raw file](https://github.com/nativetouch/gonfork/blob/a1647f1dd593800e0c10117bd95e5fed47fb6b15/nfork/inbound.go#L308)):*
<details><summary><i>Previously, JesseEmond (JesseEmond) wrote…</i></summary>
> I guess we can remove this commented line now (and get rid of `parseAddr` at the same time if that's its only usage).
</details>
Done.

---

*[nfork/inbound.go, line 322 \[r2\]](https://reviewable.io:443/reviews/nativetouch/gonfork/1#-KIZ9ciSBM0CusGSrAKO:-KIZFGOuRs2Mo03A21S6:-499146009) ([raw file](https://github.com/nativetouch/gonfork/blob/a1647f1dd593800e0c10117bd95e5fed47fb6b15/nfork/inbound.go#L322)):*
<details><summary><i>Previously, anordell wrote…</i></summary>
> +1. Or comment if else
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/1)*

**Comment by anordell** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/1)*

**Comment by anordell** [comment]
:+1: 

<details><summary><i>Previously, aluguern (Ariel Luguern) wrote…</i></summary>
> #### Plat 1045 fork to staging
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/1#-:-KIZGBD6qZmCcxfAPOT8:-510466975)*

**Comment by JesseEmond** [comment]
:+1:

<details><summary><i>Previously, anordell wrote…</i></summary>
> :+1: 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/1#-:-KIZHqoGaztuAOOZSi6m:676269983)*

**Pull request merged**
