### PR TITLE
feature/PLAT-1730 : Port to go1.6

### PR DESCRIPTION
**Pull request by aluguern**
This change is [Reviewable](https://reviewable.io/reviews/nativetouch/gonfork/7)

### CODE REVIEW

**Comment by alkhatib** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/7)*

**Comment by alkhatib** [comment]
:+1:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/7#-:-KW8wmeZXROqKHLOsxHo:bb6mt9b)*

**Comment by anordell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[nfork/stats.go, line 106 at r1](https://reviewable.io:443/reviews/nativetouch/gonfork/7#-KW8x388q-QX1wazckCa:-KW8x388q-QX1wazckCb:bmt6y67) ([raw file](https://github.com/nativetouch/gonfork/blob/3f4eba57bf8e840ef7284097d6ca1277768535cc/nfork/stats.go#L106)):*
> ```Go
> // Copy copies the object.
> func (recorder *StatsRecorder) Copy() *StatsRecorder {
> 	return &StatsRecorder{
> ```

Lock the mutex?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/7)*

**Comment by aluguern** [comment]
*[nfork/stats.go, line 106 at r1](https://reviewable.io:443/reviews/nativetouch/gonfork/7#-KW8x388q-QX1wazckCa:-KW93uT266jY7xoYOpGx:b-896fix) ([raw file](https://github.com/nativetouch/gonfork/blob/3f4eba57bf8e840ef7284097d6ca1277768535cc/nfork/stats.go#L106)):*
<details><summary><i>Previously, anordell wrote…</i></summary>
> Lock the mutex?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/7)*

**Comment by anordell** [comment]
:+1: 

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/7#-:-KW9EdiWd8Vez2Qk2pNk:b-8fx2u7)*

**Comment by anordell** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nativetouch/gonfork/7)*

**Pull request merged**
